name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: false # instalaremos manualmente
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # sin cache pnpm porque no tenemos pnpm-lock.yaml en el repo
      - name: Install
        run: pnpm install --frozen-lockfile=false
      - name: Lint
        run: pnpm lint
      - name: Typecheck
        run: pnpm typecheck
      - name: Unit tests
        run: pnpm test:unit
